name: Draft a Release

on:
  push: 
    tags:
      - '*'
env:
    VERSION: 1.2.1
jobs:
  draft-a-release:
    name: Draft a Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - name: Generate Release
      run: |
        dotnet pack OpenSearch.sln --configuration Release
        mkdir artifacts 
        for file in `ls src/*/bin/Release/*.nupkg`; do; cp $file artifacts; done
        tar -czf artifacts.tar.gz artifacts
    - name: Draft a release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        files: |
          artifacts.tar.gz
